cueDefinitions = {
    "positiveExpression": {
        "cue": "Smile / positive expression",
        "detectionParameters": [
            "mouth corner lift",
            "mouth width / smile-like mouth shape",
            "eyebrow raise",
            "camera-facing face",
            "low head-motion during the segment",
        ],
        "detectionMeaning": "Mouth-width, mouth-corner lift, eyebrow-raise, camera-facing, and low-motion proxies.",
        "semanticPurpose": "Smiling and positive delivery can show warmth, friendliness, and personability in an interview.",
        "safeInterpretation": "You appeared visually positive during this segment. This is a visual proxy, not an emotion claim.",
    },
    "cameraFacing": {
        "cue": "Eye contact / camera-facing attention",
        "detectionParameters": [
            "YOLOv11 face box",
            "gaze proxy from nose/face centering",
            "head pose proxy toward camera",
            "eye-openness balance when Face Mesh is available",
            "per-recording adaptive cue calibration",
        ],
        "detectionMeaning": "YOLOv11 face position, face/nose centering, and eye-openness balance compared with this recording's own visual baseline.",
        "semanticPurpose": "Eye contact is important for professional and formal interactions, especially in webcam interviews.",
        "safeInterpretation": "You appeared visually oriented toward the camera during this segment.",
    },
    "neutralExpression": {
        "cue": "Neutral composed expression",
        "detectionParameters": [
            "camera-facing face",
            "low head movement",
            "low posture movement",
            "low facial-expression movement over time",
            "no recent expression spikes",
            "per-recording adaptive cue calibration",
        ],
        "detectionMeaning": "Camera-facing face, stable head/posture, low facial-expression movement, and quiet expression changes relative to this recording.",
        "semanticPurpose": "A neutral, composed expression can support clear and professional delivery.",
        "safeInterpretation": "Your expression appeared visually composed during this segment.",
    },
    "tensionLikeInstability": {
        "cue": "Tension-like nervous expression",
        "detectionParameters": [
            "facial movement instability",
            "blink-like eye-openness changes",
            "head movement spikes",
            "posture movement spikes",
            "recent expression spike count",
            "per-recording adaptive cue calibration",
        ],
        "detectionMeaning": "Repeated facial, blink-like, head, or posture movement that stands out from this recording's own movement baseline.",
        "semanticPurpose": "Identify moments where delivery may visually appear less settled so the interviewee can review confidence cues.",
        "safeInterpretation": "This segment had visual instability that may be worth reviewing.",
    },
    "headMovement": {
        "cue": "Head movement",
        "detectionParameters": [
            "nose landmark movement over time",
            "vertical nose movement for nodding",
            "nose position below face center for looking down",
            "repeated head shifts",
        ],
        "detectionMeaning": "Nose landmark movement, repeated vertical movement for nodding, looking down, or repeated head shifts.",
        "semanticPurpose": "Detect possible engagement, emphasis, distraction, or disengagement patterns.",
        "safeInterpretation": "This segment contained noticeable head movement.",
    },
    "posture": {
        "cue": "Posture",
        "detectionParameters": [
            "left/right shoulder landmarks",
            "shoulder tilt relative to shoulder width",
            "posture change over time",
            "upper-body pose presence",
        ],
        "detectionMeaning": "Shoulder alignment, upper-body stability, and posture shifts.",
        "semanticPurpose": "Evaluate formal visual presence, stable demeanor, and confidence-related visual cues.",
        "safeInterpretation": "Your posture appeared stable or shifted during this segment.",
    },
    "possibleFidgeting": {
        "cue": "Fidgeting",
        "detectionParameters": [
            "rapid head movement",
            "posture movement",
            "blink-like eye-openness changes",
            "recent movement spike count",
        ],
        "detectionMeaning": "Repeated quick body/head movement changes, posture movement, and blink-like eye-openness changes.",
        "semanticPurpose": "Identify moments of visual restlessness that may affect formal delivery.",
        "safeInterpretation": "This segment may include fidgeting-like movement.",
    },
    "framing": {
        "cue": "Face framing and distance",
        "detectionParameters": [
            "YOLOv11 face center and box size",
            "distance from the frame edges",
            "face count",
        ],
        "detectionMeaning": "YOLO face placement, scale, edge clearance, and number of detected faces.",
        "semanticPurpose": "Help keep the speaker clearly framed without inferring anything about the person.",
        "safeInterpretation": "The camera framing may be worth adjusting or using as a good reference.",
    },
    "visibility": {
        "cue": "Visual detection reliability",
        "detectionParameters": [
            "YOLOv11 confidence",
            "YOLO face presence",
            "MediaPipe face-mesh presence",
            "MediaPipe pose presence",
        ],
        "detectionMeaning": "Whether the visual detectors had a clear, consistent view of the face and upper body.",
        "semanticPurpose": "Separate camera or detector limitations from delivery coaching cues.",
        "safeInterpretation": "Visibility or detector reliability was limited during this segment.",
    },
    "videoQuality": {
        "cue": "Lighting and image clarity",
        "detectionParameters": [
            "frame brightness",
            "frame contrast",
            "Laplacian sharpness proxy",
        ],
        "detectionMeaning": "Simple image-level proxies for dimness, overexposure, low contrast, and blur.",
        "semanticPurpose": "Identify recording conditions that can affect both presentation and detector accuracy.",
        "safeInterpretation": "The lighting or image clarity may have limited the recording during this segment.",
    },
    "eyeActivity": {
        "cue": "Eye openness and blink-like activity",
        "detectionParameters": [
            "MediaPipe eye openness",
            "left/right eye balance",
            "recent eye-openness change",
        ],
        "detectionMeaning": "Eye openness and blink-like changes measured from face landmarks.",
        "semanticPurpose": "Offer a timestamp for reviewing eye visibility and rapid blink-like motion in context.",
        "safeInterpretation": "Eye openness or blink-like movement changed during this segment.",
    },
    "expressiveness": {
        "cue": "Facial expressiveness",
        "detectionParameters": [
            "eyebrow raise",
            "mouth openness",
            "mouth movement over time",
            "facial movement over time",
        ],
        "detectionMeaning": "Landmark-based brow and mouth movement proxies; this does not identify an emotion.",
        "semanticPurpose": "Find visually expressive or speech-like delivery moments for playback review.",
        "safeInterpretation": "This segment contained visible brow or mouth activity.",
    },
    "headOrientation": {
        "cue": "Head orientation",
        "detectionParameters": [
            "signed nose offset inside the YOLO face box",
            "eye-line tilt",
            "horizontal nose movement",
        ],
        "detectionMeaning": "Head turn, tilt, and lateral movement proxies from face and pose landmarks.",
        "semanticPurpose": "Locate orientation changes that may affect camera-facing delivery.",
        "safeInterpretation": "Your head orientation changed during this segment.",
    },
    "bodyAlignment": {
        "cue": "Upper-body alignment",
        "detectionParameters": [
            "shoulder tilt",
            "shoulder-to-hip horizontal offset",
            "upper-body center offset",
        ],
        "detectionMeaning": "Pose-landmark proxies for shoulder alignment, lateral leaning, and body centering.",
        "semanticPurpose": "Support review of comfortable, stable webcam positioning.",
        "safeInterpretation": "Your upper-body alignment or position changed during this segment.",
    },
    "handActivity": {
        "cue": "Visible hand activity",
        "detectionParameters": [
            "MediaPipe wrist landmarks",
            "wrist movement over time",
            "wrists above shoulder level",
        ],
        "detectionMeaning": "Visible wrist motion and raised-hand proxies when MediaPipe can see the upper body.",
        "semanticPurpose": "Locate gestures for review without assigning intent or quality to them.",
        "safeInterpretation": "Visible hand movement occurred during this segment.",
    },
}


eventCueMap = {
    "cameraFacing": "cameraFacing",
    "lookingAway": "cameraFacing",
    "positiveExpression": "positiveExpression",
    "neutralExpression": "neutralExpression",
    "tensionLikeInstability": "tensionLikeInstability",
    "highHeadMovement": "headMovement",
    "nodding": "headMovement",
    "lookingDown": "headMovement",
    "stablePosture": "posture",
    "postureShift": "posture",
    "possibleFidgeting": "possibleFidgeting",
    "faceMissing": "visibility",
    "poseMissing": "visibility",
    "centeredFraming": "framing",
    "offCenterFraming": "framing",
    "faceTooClose": "framing",
    "faceTooFar": "framing",
    "facePartiallyOutOfFrame": "framing",
    "multipleFaces": "framing",
    "lowFaceConfidence": "visibility",
    "faceMeshMissing": "visibility",
    "dimLighting": "videoQuality",
    "overexposedLighting": "videoQuality",
    "lowContrast": "videoQuality",
    "blurryImage": "videoQuality",
    "eyesClosedLike": "eyeActivity",
    "rapidBlinkLikeActivity": "eyeActivity",
    "eyebrowRaise": "expressiveness",
    "mouthOpen": "expressiveness",
    "speechLikeMouthActivity": "expressiveness",
    "headTurnedLeft": "headOrientation",
    "headTurnedRight": "headOrientation",
    "headTilt": "headOrientation",
    "lateralHeadMovement": "headOrientation",
    "shoulderTilt": "bodyAlignment",
    "bodyLean": "bodyAlignment",
    "bodyOffCenter": "bodyAlignment",
    "handGestureActivity": "handActivity",
    "handsRaised": "handActivity",
}


eventDescriptions = {
    "cameraFacing": "You appeared visually oriented toward the camera during this segment, which supports eye-contact practice.",
    "lookingAway": "Camera-facing attention appeared lower during this segment, which may be worth reviewing for eye-contact practice.",
    "positiveExpression": "You appeared visually positive during this segment. This is a simple proxy, not an emotion claim.",
    "neutralExpression": "Your expression appeared visually composed during this segment.",
    "tensionLikeInstability": "This segment had visual instability that may be worth reviewing as a tension-like delivery cue.",
    "highHeadMovement": "This segment contained noticeable head movement.",
    "nodding": "This segment included repeated vertical head movement that may be worth reviewing as emphasis.",
    "lookingDown": "Your head position visually shifted downward during this segment.",
    "stablePosture": "Your posture appeared visually stable during this segment.",
    "postureShift": "Your posture visually shifted during this segment.",
    "possibleFidgeting": "This segment may include fidgeting-like movement.",
    "faceMissing": "No face was detected during this segment.",
    "poseMissing": "No upper-body pose was detected during this segment.",
    "centeredFraming": "Your face appeared comfortably centered in the camera frame during this segment.",
    "offCenterFraming": "Your face moved noticeably away from the center of the camera frame.",
    "faceTooClose": "Your face occupied a large portion of the frame; consider adding a little camera distance.",
    "faceTooFar": "Your face appeared small in the frame; moving closer may improve visual clarity.",
    "facePartiallyOutOfFrame": "The YOLO face box reached the edge of the frame during this segment.",
    "multipleFaces": "YOLO detected more than one face during this segment, which may affect cue reliability.",
    "lowFaceConfidence": "YOLO face confidence was low during this segment; treat other face cues cautiously.",
    "faceMeshMissing": "YOLO found a face but MediaPipe could not produce a face mesh during this segment.",
    "dimLighting": "The frame appeared dim during this segment.",
    "overexposedLighting": "The frame appeared very bright during this segment.",
    "lowContrast": "The frame had low visual contrast during this segment.",
    "blurryImage": "The image sharpness proxy was low during this segment.",
    "eyesClosedLike": "Eye openness was low during this segment; review it in context because a normal blink can trigger this proxy.",
    "rapidBlinkLikeActivity": "Repeated eye-openness changes occurred during this segment.",
    "eyebrowRaise": "Your eyebrows appeared raised during this segment.",
    "mouthOpen": "Your mouth appeared open during this segment, often consistent with speaking.",
    "speechLikeMouthActivity": "Visible mouth movement occurred during this segment, which can be consistent with active speaking.",
    "headTurnedLeft": "Your head appeared turned toward the left side of the image during this segment.",
    "headTurnedRight": "Your head appeared turned toward the right side of the image during this segment.",
    "headTilt": "Your eye line appeared tilted during this segment.",
    "lateralHeadMovement": "Your head moved laterally during this segment.",
    "shoulderTilt": "Your shoulders appeared noticeably tilted during this segment.",
    "bodyLean": "Your shoulders shifted laterally relative to your hips during this segment.",
    "bodyOffCenter": "Your upper body appeared away from the center of the frame during this segment.",
    "handGestureActivity": "Visible hand movement occurred during this segment; review whether it supported your delivery.",
    "handsRaised": "One or both visible wrists moved above shoulder level during this segment.",
}


def getCueInfo(eventType):
    cueKey = eventCueMap.get(eventType, eventType)
    return cueDefinitions.get(
        cueKey,
        {
            "cue": eventType,
            "detectionParameters": ["rule-based visual cue"],
            "detectionMeaning": "Rule-based visual cue.",
            "semanticPurpose": "Interview delivery review.",
            "safeInterpretation": "This segment may be worth reviewing.",
        },
    )


def getEventDescription(eventType):
    return eventDescriptions.get(eventType, getCueInfo(eventType)["safeInterpretation"])
