import type { EvidenceEvent, TranscriptArtifact } from "@/types/local";

const overlaps = (startA: number, endA: number, startB: number, endB: number) => Math.min(endA, endB) > Math.max(startA, startB);
const excerpt = (segments: TranscriptArtifact["segments"], start: number, end: number) => segments.filter((segment) => overlaps(start, end, segment.start, segment.end)).map((segment) => segment.text).join(" ").trim();
const moment = (base: EvidenceEvent | { startTime: number; endTime: number; eventType: string; measurements?: Record<string, unknown>; reliability?: string }, visuals: EvidenceEvent[], transcript: TranscriptArtifact, category: string, classification: "strength" | "review" | "context", explanation: string, coachingRecommendation: string, override?: string) => ({ startTime: base.startTime, endTime: base.endTime, durationSeconds: Math.max(0, base.endTime - base.startTime), transcriptExcerpt: override || excerpt(transcript.segments, base.startTime, base.endTime), audioEvents: [base.eventType], audioMeasurements: base.measurements || {}, visualEvents: visuals.map((item) => item.eventType), visualEvidence: visuals.map((item) => ({ eventType: item.eventType, startTime: item.startTime, endTime: item.endTime, reliability: item.reliability, measurements: item.measurements })), alignmentCategory: category, classification, explanation, coachingRecommendation, evidenceSources: ["audio", "visual", "transcript"], confidence: base.reliability || "medium" });

export function alignMultimodalEvents(transcript: TranscriptArtifact, responseAnalysis: Record<string, unknown>, audioEvents: EvidenceEvent[], visualEvents: EvidenceEvent[]): Array<Record<string, unknown>> {
  const items: Array<Record<string, unknown>> = [];
  for (const audio of audioEvents) {
    const visuals = visualEvents.filter((visual) => overlaps(audio.startTime, audio.endTime, visual.startTime, visual.endTime)); const types = new Set(visuals.map((item) => item.eventType));
    if (audio.eventType === "longPause" && types.has("lookingDown")) items.push(moment(audio, visuals, transcript, "pauseWithDownwardGaze", "review", "A measurable pause overlapped with a downward head-position cue.", "Replay the moment and decide whether the pause looked intentional; return toward the camera before the next key point."));
    else if (audio.eventType === "rapidSpeech" && (types.has("highHeadMovement") || types.has("lateralHeadMovement"))) items.push(moment(audio, visuals, transcript, "rapidSpeechWithMovement", "review", "A high local word rate overlapped with noticeable head movement.", "Practice the same phrase slightly slower with smaller intentional movement."));
    else if (audio.eventType === "strongVocalEmphasis" && types.has("handGestureActivity")) items.push(moment(audio, visuals, transcript, "emphasisWithGesture", "strength", "A rise in vocal energy aligned with a visible hand-gesture cue.", "Review whether the gesture and emphasis supported the same important phrase; preserve it if they did."));
    else if (audio.eventType === "lowVolume" && visuals.length) items.push(moment(audio, visuals, transcript, "quietSpeechWithVisibleDelivery", "review", "A measurably quiet passage overlapped with visible delivery evidence.", "Replay the phrase for microphone distance and audibility before changing visual delivery."));
  }
  for (const phrase of (responseAnalysis.strongPhrases as Array<{ startTime: number; endTime: number; text: string; reasons: string[] }> || [])) {
    const visuals = visualEvents.filter((visual) => overlaps(phrase.startTime, phrase.endTime, visual.startTime, visual.endTime)); const strengths = visuals.filter((item) => ["cameraFacing", "stablePosture", "positiveExpression", "centeredFraming"].includes(item.eventType)); const reviews = visuals.filter((item) => ["lookingAway", "lookingDown"].includes(item.eventType)); const base = { startTime: phrase.startTime, endTime: phrase.endTime, eventType: "strongResponseContent", measurements: { strongPhraseReasons: phrase.reasons }, reliability: "medium" };
    if (strengths.length) items.push(moment(base, strengths, transcript, "strongContentWithVisualSupport", "strength", "A specific action or result phrase aligned with a visual strength cue.", "Use this timestamp as a reference for delivering another important example.", phrase.text));
    if (reviews.length) items.push(moment(base, reviews, transcript, "strongContentWithAttentionShift", "review", "A strong, specific phrase occurred while camera-facing attention was lower.", "Practice returning toward the camera before stating the result or key takeaway.", phrase.text));
  }
  return items.filter((item, index, all) => all.findIndex((other) => other.alignmentCategory === item.alignmentCategory && other.startTime === item.startTime && other.endTime === item.endTime) === index).sort((a, b) => Number(a.startTime) - Number(b.startTime));
}
