import type { EvidenceEvent } from "@/types/local";

const rating = (score: number | null) => score === null ? "Unavailable" : score >= 85 ? "Strong evidence" : score >= 70 ? "Generally effective" : score >= 55 ? "Mixed evidence" : "Practice priority";
const score = (value: number | null, confidence: string, evidence: string[], positives: string[], practice: string[], formula: string, componentBreakdown: Record<string, unknown> = {}) => ({ score: value === null ? null : Math.max(0, Math.min(100, Number(value.toFixed(1)))), rating: rating(value), confidence, dataCoverage: value === null ? "unavailable" : "available", evidence, positiveObservations: positives, practiceAreas: practice, formula, componentBreakdown });
const unavailable = (reason: string) => score(null, "unavailable", [reason], [], [], "Excluded because the required modality was unavailable.");

export function buildCoachingScores(mediaInfo: { hasAudio: boolean; hasVideo: boolean }, audioFeatures: Record<string, unknown>, audioEvents: EvidenceEvent[], response: Record<string, unknown>, visualEvents: EvidenceEvent[], moments: Array<Record<string, unknown>>): Record<string, unknown> {
  const audioAvailable = audioFeatures.available === true; const numeric = (value: unknown) => typeof value === "number" ? value : null;
  const recordingQuality = !audioAvailable ? unavailable("No audible decoded waveform was available.") : (() => { const clipping = numeric(audioFeatures.clippingPercentage) || 0; const dropout = numeric(audioFeatures.dropoutRatio) || 0; const level = numeric(audioFeatures.overallRmsDb); const snr = numeric(audioFeatures.snrProxyDb); let value = 100 - Math.min(clipping * 8, 35) - Math.min(dropout * 100, 30); if (level !== null && level < -40) value -= Math.min((-40 - level) * 1.5, 25); if (snr !== null && snr < 15) value -= Math.min((15 - snr) * 1.5, 20); return score(value, "high", [`Overall RMS level: ${level ?? "unavailable"} dBFS`, `Clipping: ${clipping.toFixed(3)}%`, `SNR proxy: ${snr ?? "unavailable"} dB`], clipping < 0.1 ? ["Very little digital clipping was measured."] : [], clipping >= 0.1 ? ["Reduce microphone gain or increase microphone distance to avoid clipping."] : [], "100 minus clipping, dropout, low-level, and low-SNR proxy deductions."); })();
  const vocal = !audioAvailable ? unavailable("No audible decoded waveform was available for vocal-delivery analysis.") : (() => { const pace = numeric(audioFeatures.speechRateWpm); const energy = numeric(audioFeatures.energyVariationDb); const pauses = audioEvents.filter((item) => item.eventType === "longPause").length; let value = 75; if (pace !== null) value += pace >= 105 && pace <= 175 ? 12 : -Math.min(Math.abs(pace - (pace < 105 ? 105 : 175)) * 0.25, 25); if (energy !== null) value += energy >= 6 ? 6 : -6; value -= Math.min(pauses * 2, 10); return score(value, "medium", [`Speech rate: ${pace ?? "unavailable"} WPM`, `Energy range: ${energy ?? "unavailable"} dB`, `Long pauses: ${pauses}`], pace !== null && pace >= 105 && pace <= 175 ? ["The measured word rate fell in a broadly conversational practice range."] : [], pace !== null && (pace < 105 || pace > 175) ? ["Rehearse near a conversational 105–175 words per minute without forcing a speaking style."] : [], "Base 75 with observable pace, energy, and pause adjustments."); })();
  const verbalRubric = response.rubric as Record<string, { score?: number }> | undefined; const verbal = !response.available ? unavailable("No transcript was available for deterministic response analysis.") : score(verbalRubric?.overallVerbalResponse?.score ?? null, String(response.confidence || "medium"), [`Words: ${String((response.metrics as Record<string, unknown>)?.wordCount ?? 0)}`, `Fillers per 100 words: ${String((response.metrics as Record<string, unknown>)?.fillerRatePer100Words ?? 0)}`], [], (response.practiceAreas as string[] || []), "Deterministic answer-structure and specificity rubric.");
  const visual = !mediaInfo.hasVideo ? unavailable("No video was available for visual-delivery analysis.") : visualEvents.length === 0 ? unavailable("No reliable visual events were available.") : (() => { const strengths = visualEvents.filter((item) => ["cameraFacing", "stablePosture", "centeredFraming", "positiveExpression"].includes(item.eventType)).length; const reviews = visualEvents.filter((item) => ["lookingAway", "lookingDown", "postureShift", "highHeadMovement", "faceMissing", "dimLighting"].includes(item.eventType)).length; return score(70 + Math.min(strengths * 5, 20) - Math.min(reviews * 4, 28), "medium", [`Visual strength-style events: ${strengths}`, `Visual review-style events: ${reviews}`], strengths ? ["Observed visual delivery included timestamped strength-style cues."] : [], reviews ? ["Replay timestamped visual review cues in context before changing delivery."] : [], "Base 70 with capped additions for observable visual support and deductions for review cues."); })();
  const alignment = !mediaInfo.hasAudio || !mediaInfo.hasVideo ? unavailable("At least audio and video are required for multimodal alignment scoring.") : (() => { const strengths = moments.filter((item) => item.classification === "strength").length; const reviews = moments.filter((item) => item.classification === "review").length; return score(70 + Math.min(strengths * 6, 24) - Math.min(reviews * 5, 25), moments.length ? "medium" : "limited", [`Aligned strength moments: ${strengths}`, `Aligned review moments: ${reviews}`], moments.filter((item) => item.classification === "strength").map((item) => String(item.explanation)).slice(0, 3), moments.filter((item) => item.classification === "review").map((item) => String(item.coachingRecommendation)).slice(0, 3), "Base 70 with capped additions for aligned strengths and deductions for aligned review moments."); })();
  const scores = { audioRecordingQuality: recordingQuality, vocalDelivery: vocal, verbalResponseQuality: verbal, visualDelivery: visual, multimodalAlignment: alignment };
  const weights: Record<keyof typeof scores, number> = { audioRecordingQuality: 0.15, vocalDelivery: 0.2, verbalResponseQuality: 0.3, visualDelivery: 0.2, multimodalAlignment: 0.15 }; const included = (Object.keys(scores) as Array<keyof typeof scores>).filter((key) => scores[key].score !== null); const totalWeight = included.reduce((sum, key) => sum + weights[key], 0);
  const overall = included.length ? included.reduce((sum, key) => sum + Number(scores[key].score) * weights[key] / totalWeight, 0) : null; const components = Object.fromEntries(included.map((key) => [key, { score: scores[key].score, normalizedWeight: Number((weights[key] / totalWeight).toFixed(4)) }]));
  return { analysisVersion: "browser-scores-v1", scores: { ...scores, overallInterviewPracticeDelivery: overall === null ? unavailable("No usable audio, transcript, or visual evidence was available.") : score(overall, included.length === 5 ? "high" : included.length >= 3 ? "medium" : "limited", included.map((key) => `${key}: ${scores[key].score}`), [], [], "Weighted mean of available modality scores; unavailable components are excluded and remaining weights are renormalized.", { components, excludedComponents: (Object.keys(scores) as Array<keyof typeof scores>).filter((key) => !included.includes(key)) }) }, safetyNote: "These are explainable interview-practice coaching scores. They are not hiring scores and do not assess personality, honesty, intelligence, emotion, mental state, protected characteristics, or suitability for employment." };
}
