import type { LocalSessionContext, TranscriptArtifact } from "@/types/local";

type Embed = (texts: string[]) => Promise<number[][]>;
const cosine = (left: number[], right: number[]) => { const dot = left.reduce((sum, value, index) => sum + value * (right[index] ?? 0), 0); const norm = Math.sqrt(left.reduce((sum, value) => sum + value * value, 0)) * Math.sqrt(right.reduce((sum, value) => sum + value * value, 0)); return norm ? dot / norm : 0; };

export async function analyzeSemanticResponse(transcript: TranscriptArtifact, context: LocalSessionContext, embed: Embed): Promise<Record<string, unknown>> {
  const segments = transcript.segments.filter((item) => item.text.trim());
  if (!transcript.text.trim() || !segments.length) return { analysisVersion: "browser-semantic-v1", available: false, warnings: ["No transcript segments were available for semantic analysis."] };
  const queries = [context.interviewQuestion, context.targetRole || "", context.jobDescription || "", context.desiredCompetencies || ""].filter(Boolean); const embeddings = await embed([...queries, ...segments.map((item) => item.text)]); const query = embeddings[0]; const role = embeddings[1]; const offset = queries.length; const assessments = segments.map((segment, index) => ({ startTime: segment.start, endTime: segment.end, text: segment.text, questionRelevance: query ? cosine(query, embeddings[offset + index]) : null, roleRelevance: role ? cosine(role, embeddings[offset + index]) : null }));
  const relevance = assessments.map((item) => Number(item.questionRelevance ?? 0)); const highest = relevance.length ? Math.max(...relevance) : 0; const lowest = relevance.length ? Math.min(...relevance) : 0;
  const redundantPairs: Array<Record<string, unknown>> = []; for (let first = 0; first < assessments.length; first += 1) for (let second = first + 1; second < assessments.length; second += 1) { const similarity = cosine(embeddings[offset + first], embeddings[offset + second]); if (similarity >= 0.88) redundantPairs.push({ firstStartTime: assessments[first].startTime, secondStartTime: assessments[second].startTime, similarity: Number(similarity.toFixed(3)) }); }
  return { analysisVersion: "browser-semantic-v1", available: true, questionRelevance: query ? Number((relevance.reduce((sum, value) => sum + value, 0) / relevance.length).toFixed(3)) : null, roleContextRelevance: role ? Number((assessments.reduce((sum, item) => sum + Number(item.roleRelevance ?? 0), 0) / assessments.length).toFixed(3)) : null, strongestRelevantSegments: assessments.filter((item) => item.questionRelevance !== null && item.questionRelevance >= Math.max(0.25, highest - 0.08)).map((item) => ({ ...item, marker: "mostRelevant" })), vagueSegments: assessments.filter((item) => item.questionRelevance !== null && item.questionRelevance <= Math.min(0.1, lowest + 0.03)).map((item) => ({ ...item, marker: "possibleTopicDrift", vagueOrOffTopic: true })), segmentAssessments: assessments, semanticRedundancy: redundantPairs, warnings: [] };
}
